import test from 'node:test';
import assert from 'node:assert/strict';
import { scoreFuturesEvidence } from '../src/core/futures-evidence-scoring.js';

const row = (overrides = {}) => ({ fresh: true, bias: 'bullish', hist: 2, sig: 1, gap: 1, regime: 'TRENDING_LONG', quote: { close: 100 }, external_evidence: { cannon: { available: true, market_code: 'EP', freshness: { status: 'FRESH' }, short: { up: 'UP', down: null }, long: { up: 'UP', down: null }, change_pct: 0.5, levels: { Pivot: 98, R1: 110 }, reaction_zones: { high_30d: 120, low_30d: 80, high_52w: 130, low_52w: 70 } } }, ...overrides });

test('aligned long is A agreement and preserves native semantics', () => { const x = scoreFuturesEvidence(row()); assert.equal(x.setup_quality, 'A'); assert.equal(x.futures_evidence_state.cross_provider, 'AGREEMENT_LONG'); assert.equal(x.futures_evidence_state.cannon_native.rule, 'ALIGN_LONG'); });
test('aligned short is A agreement', () => { const x = scoreFuturesEvidence(row({ bias: 'bearish', regime: 'TRENDING_SHORT', external_evidence: { cannon: { ...row().external_evidence.cannon, market_code: 'ENQ', short: { up: null, down: 'DOWN' }, long: { up: null, down: 'DOWN' } } } })); assert.equal(x.setup_quality, 'A'); assert.equal(x.futures_evidence_state.cross_provider, 'AGREEMENT_SHORT'); });
test('partial or aligned opposite provider is conflict, not cancellation or rejection', () => { for (const cannon of [{ short: { up: 'UP', down: null }, long: { up: null, down: null } }, { short: { up: 'UP', down: null }, long: { up: 'UP', down: null } }]) { const x = scoreFuturesEvidence(row({ bias: 'bearish', external_evidence: { cannon: { ...row().external_evidence.cannon, market_code: 'KCE', short: cannon.short, long: cannon.long } } })); assert.equal(x.futures_evidence_state.cross_provider, 'CONFLICT'); assert.equal(x.setup_quality, 'D'); assert.equal(x.entry_quality, 'CAUTION'); assert.notEqual(x.score, -99); } });
test('unmapped Cannon remains TV-only with medium confidence', () => { const x = scoreFuturesEvidence(row({ external_evidence: { cannon: { available: false, freshness: { status: 'UNAVAILABLE' }, short: {}, long: {}, levels: {}, reaction_zones: {} } } })); assert.equal(x.futures_evidence_state.cross_provider, 'TV_ONLY'); assert.equal(x.futures_evidence_state.data_confidence, 'MEDIUM'); });
test('contradictory raw Cannon slots reject for manual review', () => { const x = scoreFuturesEvidence(row({ external_evidence: { cannon: { ...row().external_evidence.cannon, short: { up: 'UP', down: 'DOWN' } } } })); assert.equal(x.futures_evidence_state.cannon_native.rule, 'MANUAL_REVIEW'); assert.equal(x.eligibility, 'REJECT'); assert.equal(x.score, -99); });
test('tier thresholds and flat filter are native modifiers only', () => { const adverse = scoreFuturesEvidence(row({ external_evidence: { cannon: { ...row().external_evidence.cannon, change_pct: -1.1 } } })); assert.ok(adverse.futures_evidence_state.cannon_native.modifiers.includes('ADVERSE_MOMENTUM')); const tier3 = scoreFuturesEvidence(row({ external_evidence: { cannon: { ...row().external_evidence.cannon, market_code: 'CLE', change_pct: -0.6 } } })); assert.ok(tier3.futures_evidence_state.cannon_native.modifiers.includes('ADVERSE_MOMENTUM')); const eu = scoreFuturesEvidence(row({ external_evidence: { cannon: { ...row().external_evidence.cannon, market_code: 'EU6', change_pct: 0.1 } } })); assert.ok(eu.futures_evidence_state.cannon_native.modifiers.includes('EU6_FLAT_FILTER')); });
test('tactical and structural location context is not separately stacked into score', () => { const x = scoreFuturesEvidence(row({ external_evidence: { cannon: { ...row().external_evidence.cannon, levels: { Pivot: 98, R1: 100.2 }, reaction_zones: { high_30d: 100.2, low_30d: 80, high_52w: 130, low_52w: 70 } } } })); assert.equal(x.futures_evidence_state.location.tactical_state, 'HEADWIND'); assert.equal(x.futures_evidence_state.location.structural_state, 'NEAR_30D_HIGH'); assert.equal(x.score, 7); const noLevels = scoreFuturesEvidence(row({ external_evidence: { cannon: { ...row().external_evidence.cannon, levels: {}, reaction_zones: {} } } })); assert.equal(noLevels.futures_evidence_state.location.tactical_state, 'UNKNOWN'); });
