import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
const script=fileURLToPath(new URL('../scripts/ingest-llm-decision.mjs',import.meta.url));
const decision=(strategy,symbol='NASDAQ:TEST')=>({strategy,symbol,decision:'WATCH',direction:'LONG',confidence:.7,rationale:['r'],supporting_evidence:['e'],conflicting_evidence:[],missing_or_unknown:[],manual_checks:[],invalidation_conditions:[],final_comment:'review'});
function setup(){const d=mkdtempSync(join(tmpdir(),'llm-ingest-')); mkdirSync(join(d,'evidence/latest'),{recursive:true}); mkdirSync(join(d,'reports/2026-08-14/llm-decisions'),{recursive:true}); const pkg={strategy_contexts:{momentum_etf:{strategy_context_version:'v1'}},candidates_by_strategy:{momentum_etf:[{symbol:'NASDAQ:TEST',score:5,status:'REVIEW'}]}}; const pp=join(d,'evidence/latest/all-strategies-llm-input.json'); writeFileSync(pp,JSON.stringify(pkg)); const h=createHash('sha256').update(readFileSync(pp)).digest('hex'); const req={strategy:'momentum_etf',strategy_context_version:'v1',candidates:pkg.candidates_by_strategy.momentum_etf}; const rp=join(d,'reports/2026-08-14/llm-decisions/momentum_etf.request.json'); writeFileSync(rp,JSON.stringify(req)); writeFileSync(join(d,'reports/2026-08-14/llm-decisions/manifest.json'),JSON.stringify({decisions:[{strategy:'momentum_etf',input_package_hash:h,context_version:'v1',status:'PENDING_PROVIDER'}]})); return {d,rp};}
test('valid single-strategy response is published and wrong/cross-strategy responses are rejected',()=>{const {d,rp}=setup(); try{const good=join(d,'good.json');writeFileSync(good,JSON.stringify({request_artifact:rp, input_package_hash:createHash('sha256').update(readFileSync(join(d,'evidence/latest/all-strategies-llm-input.json'))).digest('hex'),strategy_context_version:'v1',decisions:[decision('momentum_etf')] }));execFileSync(process.execPath,[script,good],{env:{...process.env,TRADINGVIEW_ROOT:d}});assert.equal(JSON.parse(readFileSync(join(d,'reports/2026-08-14/llm-decisions/momentum_etf.json'))).status,'VALIDATED'); const bad=join(d,'bad.json');writeFileSync(bad,JSON.stringify({request_artifact:rp,decisions:[decision('crypto','COINBASE:BTCUSD')]}));assert.throws(()=>execFileSync(process.execPath,[script,bad],{env:{...process.env,TRADINGVIEW_ROOT:d}}));assert.equal(JSON.parse(readFileSync(join(d,'reports/2026-08-14/llm-decisions/manifest.json'))).decisions[0].status,'REJECTED');}finally{rmSync(d,{recursive:true,force:true});}});
